apiVersion: v1                    
kind: Namespace
metadata:
  name: bookinfo-acm-prod                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookinfo-acm-prod
  namespace: bookinfo-acm-prod
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - bookinfo-acm-prod
