
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: bookinfo
  name: bookinfo-placement-1
  namespace: bookinfo
spec:
  clusterSelector:
    matchLabels:
      'env': 'dev'
