
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: 
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: bookinfo-dev-deployment
  name: bookinfo-dev-deployment-subscription-1
  namespace: bookinfo-dev-deployment
spec:
  channel: ggithubcom-rachnadodia-service-mesh-app-ns/ggithubcom-rachnadodia-service-mesh-app
  placement:
    placementRef:
      kind: PlacementRule
      name: bookinfo-dev-deployment-placement-1
